#
# Copyright (C) 2024 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := $(call my-dir)

ifeq ($(USES_DEVICE_VIRT_VIRTIO_COMMON),true)

# Combine ramdisk
INSTALLED_COMBINED_RAMDISK_TARGET := $(PRODUCT_OUT)/combined-ramdisk.img
INSTALLED_COMBINED_RAMDISK_TARGET_DEPS := $(PRODUCT_OUT)/ramdisk.img $(PRODUCT_OUT)/vendor_ramdisk.img
INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET := $(PRODUCT_OUT)/combined-ramdisk-recovery.img
INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET_DEPS := $(PRODUCT_OUT)/ramdisk-recovery.img $(PRODUCT_OUT)/vendor_ramdisk.img

$(INSTALLED_COMBINED_RAMDISK_TARGET): $(INSTALLED_COMBINED_RAMDISK_TARGET_DEPS)
	cat $^ > $@

$(INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET): $(INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET_DEPS)
	cat $^ > $@

.PHONY: combined-ramdisk
combined-ramdisk: $(INSTALLED_COMBINED_RAMDISK_TARGET)

.PHONY: combined-ramdisk-recovery
combined-ramdisk-recovery: $(INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET)

# Common definitions for boot managers
BOOTMGR_TOOLS_LINEAGE_BIN_DIR := prebuilts/tools-lineage/$(HOST_PREBUILT_TAG)/bin
BOOTMGR_PATH_OVERRIDE := PATH=$(BOOTMGR_TOOLS_LINEAGE_BIN_DIR):$$PATH

ifeq ($(TARGET_ARCH),arm64)
BOOTMGR_EFI_BOOT_FILENAME := BOOTAA64.EFI
else ifeq ($(TARGET_ARCH),x86_64)
BOOTMGR_EFI_BOOT_FILENAME := BOOTX64.EFI
endif

ifneq ($(LINEAGE_BUILD),)
BOOTMGR_ANDROID_DISTRIBUTION_NAME := LineageOS $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)
BOOTMGR_ANDROID_OTA_PACKAGE_NAME := lineage-$(LINEAGE_VERSION).zip
BOOTMGR_ARTIFACT_FILENAME_PREFIX := lineage-$(LINEAGE_VERSION)
BOOTMGR_THEME := lineage
else
LOCAL_BUILD_DATE := $(shell date -u +%Y%m%d)
BOOTMGR_ANDROID_DISTRIBUTION_NAME := Android $(PLATFORM_VERSION_LAST_STABLE) $(BUILD_ID)
BOOTMGR_ANDROID_OTA_PACKAGE_NAME := $(TARGET_PRODUCT)-ota-$(FILE_NAME_TAG).zip
BOOTMGR_ARTIFACT_FILENAME_PREFIX := Android-$(PLATFORM_VERSION_LAST_STABLE)-$(BUILD_ID)-$(LOCAL_BUILD_DATE)-$(TARGET_PRODUCT)
BOOTMGR_THEME := android
endif

ifeq ($(PRODUCT_IS_AUTOMOTIVE),true)
BOOTMGR_ANDROID_DISTRIBUTION_NAME += Car
else ifeq ($(PRODUCT_IS_ATV),true)
BOOTMGR_ANDROID_DISTRIBUTION_NAME += TV
endif

INSTALLED_ESPIMAGE_TARGET := $(TARGET_OUT_INTERMEDIATES)/CUSTOM_IMAGES/EFI.img
INSTALLED_ESPIMAGE_INSTALL_TARGET := $(PRODUCT_OUT)/$(BOOTMGR_ARTIFACT_FILENAME_PREFIX).img

INSTALLED_ESPIMAGE_TARGET_DEPS := \
	$(PRODUCT_OUT)/kernel \
	$(INSTALLED_COMBINED_RAMDISK_TARGET) \
	$(INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET)

INSTALLED_ESPIMAGE_INSTALL_TARGET_DEPS := \
	$(PRODUCT_OUT)/kernel \
	$(INSTALLED_COMBINED_RAMDISK_RECOVERY_TARGET) \
	$(PRODUCT_OUT)/$(BOOTMGR_ANDROID_OTA_PACKAGE_NAME)

# $(1): output file
# $(2): list of contents to include
# $(3): purpose
define create-espimage
	/bin/dd if=/dev/zero of=$(1) bs=1M count=$$($(COMMON_PATH)/.calc_fat32_img_size.sh $(2))
	$(BOOTMGR_TOOLS_LINEAGE_BIN_DIR)/mformat -F -i $(1) -v "$(3)" ::
	$(foreach content,$(2),$(BOOTMGR_TOOLS_LINEAGE_BIN_DIR)/mcopy -i $(1) -s $(content) :: &&)true
endef

# $(1): path to boot manager config file
define process-bootmgr-cfg-common
	sed -i "s|@BOOTMGR_ANDROID_DISTRIBUTION_NAME@|$(BOOTMGR_ANDROID_DISTRIBUTION_NAME)|g" $(1)
	sed -i "s|@BOOTMGR_EFI_BOOT_FILENAME@|$(BOOTMGR_EFI_BOOT_FILENAME)|g" $(1)
	sed -i "s|@STRIPPED_TARGET_BOOTMGR_KERNEL_CMDLINE@|$(strip $(TARGET_BOOTMGR_KERNEL_CMDLINE))|g" $(1)
endef

include $(call all-makefiles-under,$(LOCAL_PATH))

# Build boot manager images

ifneq ($(TARGET_BOOT_MANAGER),)

##### espimage #####

$(INSTALLED_ESPIMAGE_TARGET): $(INSTALLED_ESPIMAGE_TARGET_DEPS)
	$(hide) mkdir -p $(dir $@)
	$(call make-espimage-target,$(INSTALLED_ESPIMAGE_TARGET),$(INSTALLED_ESPIMAGE_TARGET_DEPS))

.PHONY: espimage
espimage: $(INSTALLED_ESPIMAGE_TARGET)

.PHONY: espimage-nodeps
espimage-nodeps:
	@echo "make $(INSTALLED_ESPIMAGE_TARGET): ignoring dependencies"
	$(hide) mkdir -p $(dir $@)
	$(call make-espimage-target,$(INSTALLED_ESPIMAGE_TARGET),$(INSTALLED_ESPIMAGE_TARGET_DEPS))

ALL_DEFAULT_INSTALLED_MODULES += $(PRODUCT_OUT)/EFI.img

##### espimage-install #####

$(INSTALLED_ESPIMAGE_INSTALL_TARGET): $(INSTALLED_ESPIMAGE_INSTALL_TARGET_DEPS)
	$(call make-espimage-install-target,$(INSTALLED_ESPIMAGE_INSTALL_TARGET),$(INSTALLED_ESPIMAGE_INSTALL_TARGET_DEPS))

.PHONY: espimage-install
espimage-install: $(INSTALLED_ESPIMAGE_INSTALL_TARGET)

.PHONY: espimage-install-nodeps
espimage-install-nodeps:
	@echo "make $(INSTALLED_ESPIMAGE_INSTALL_TARGET): ignoring dependencies"
	$(call make-espimage-install-target,$(INSTALLED_ESPIMAGE_INSTALL_TARGET),$(INSTALLED_ESPIMAGE_INSTALL_TARGET_DEPS))

endif # TARGET_BOOT_MANAGER

# Create vda disk image

SGDISK_EXEC := out/host/linux-x86/bin/sgdisk

DISK_VDA_SECTOR_SIZE := 512
ifeq ($(BOARD_SUPER_PARTITION_SIZE),3221225472)
	DISK_VDA_SECTORS := 8388608
	DISK_VDA_PARTITION_EFI_START_SECTOR := 2048
	DISK_VDA_PARTITION_SUPER_START_SECTOR := 264192
	DISK_VDA_PARTITION_MISC_START_SECTOR := 6555648
	DISK_VDA_PARTITION_METADATA_START_SECTOR := 6557696
	DISK_VDA_PARTITION_CACHE_START_SECTOR := 6623232
	DISK_VDA_PARTITION_BOOT_START_SECTOR := 6725632
	DISK_VDA_PARTITION_RECOVERY_START_SECTOR := 6856704
	DISK_VDA_PARTITION_EFI_SECTORS := 262144
	DISK_VDA_PARTITION_SUPER_SECTORS := 6291456
	DISK_VDA_PARTITION_MISC_SECTORS := 2048
	DISK_VDA_PARTITION_METADATA_SECTORS := 65536
	DISK_VDA_PARTITION_CACHE_SECTORS := 102400
	DISK_VDA_PARTITION_BOOT_SECTORS := 131072
	DISK_VDA_PARTITION_RECOVERY_SECTORS := 131072
else ifeq ($(BOARD_SUPER_PARTITION_SIZE),4294967296)
	DISK_VDA_SECTORS := 10485760
	DISK_VDA_PARTITION_EFI_START_SECTOR := 2048
	DISK_VDA_PARTITION_SUPER_START_SECTOR := 264192
	DISK_VDA_PARTITION_MISC_START_SECTOR := 8663040
	DISK_VDA_PARTITION_METADATA_START_SECTOR := 8665088
	DISK_VDA_PARTITION_CACHE_START_SECTOR := 8730624
	DISK_VDA_PARTITION_BOOT_START_SECTOR := 8834816
	DISK_VDA_PARTITION_RECOVERY_START_SECTOR := 8965888
	DISK_VDA_PARTITION_EFI_SECTORS := 262144
	DISK_VDA_PARTITION_SUPER_SECTORS := 8388608
	DISK_VDA_PARTITION_MISC_SECTORS := 2048
	DISK_VDA_PARTITION_METADATA_SECTORS := 65536
	DISK_VDA_PARTITION_CACHE_SECTORS := 102400
	DISK_VDA_PARTITION_BOOT_SECTORS := 131072
	DISK_VDA_PARTITION_RECOVERY_SECTORS := 131072
else
	$(error Unsupported BOARD_SUPER_PARTITION_SIZE for vda disk image creation)
endif

DISK_VDA_WRITE_PARTITIONS := \
	$(BOARD_CUSTOMIMAGES_PARTITION_LIST) \
	super \
	cache \
	boot \
	recovery

# $(1): output file
# $(2): disk name
define make-diskimage-target
	$(call pretty,"Target $(2) disk image: $(1)")
	/bin/dd if=/dev/zero of=$(1) bs=$(DISK_$(call to-upper,$(2))_SECTOR_SIZE) count=$(DISK_$(call to-upper,$(2))_SECTORS)
	/bin/sh -e $(COMMON_PATH)/config/create_partition_table.sh $(SGDISK_EXEC) $(1) $(2) $(BOARD_SUPER_PARTITION_SIZE)
	$(foreach p,$(DISK_$(call to-upper,$(2))_WRITE_PARTITIONS),\
		/bin/dd if=$(PRODUCT_OUT)/$(p).img of=$(1) bs=$(DISK_$(call to-upper,$(2))_SECTOR_SIZE) seek=$(DISK_$(call to-upper,$(2))_PARTITION_$(call to-upper,$(p))_START_SECTOR) count=$(DISK_$(call to-upper,$(2))_PARTITION_$(call to-upper,$(p))_SECTORS) conv=notrunc &&\
	)true
endef

INSTALLED_DISKIMAGE_VDA_TARGET := $(PRODUCT_OUT)/disk-vda.img
INSTALLED_DISKIMAGE_VDA_TARGET_DEPS := $(SGDISK_EXEC)
$(foreach p,$(DISK_VDA_WRITE_PARTITIONS),\
	$(eval INSTALLED_DISKIMAGE_VDA_TARGET_DEPS += $(PRODUCT_OUT)/$(p).img))
$(INSTALLED_DISKIMAGE_VDA_TARGET): $(INSTALLED_DISKIMAGE_VDA_TARGET_DEPS)
	$(call make-diskimage-target,$(INSTALLED_DISKIMAGE_VDA_TARGET),vda)

.PHONY: diskimage-vda
diskimage-vda: $(INSTALLED_DISKIMAGE_VDA_TARGET)

.PHONY: diskimage-vda-nodeps
diskimage-vda-nodeps:
	@echo "make $(INSTALLED_DISKIMAGE_VDA_TARGET): ignoring dependencies"
	$(call make-diskimage-target,$(INSTALLED_DISKIMAGE_VDA_TARGET),vda)

# Create prebuilt kernel repo

ifneq ($(LINEAGE_BUILD),)
ifneq ($(wildcard $(TARGET_KERNEL_SOURCE)/Makefile),)

INSTALLED_PREBUILT_KERNEL_REPO_DIR := out/kernel-virtio/$(TARGET_PREBUILT_KERNEL_USE)/$(TARGET_PREBUILT_KERNEL_ARCH)

INSTALLED_PREBUILT_KERNEL_REPO_KERNEL_TARGET := $(INSTALLED_PREBUILT_KERNEL_REPO_DIR)/kernel
$(INSTALLED_PREBUILT_KERNEL_REPO_KERNEL_TARGET): $(PRODUCT_OUT)/kernel
	$(call pretty,"Target prebuilt kernel repo: $@")
	mkdir -p $(INSTALLED_PREBUILT_KERNEL_REPO_DIR)
	rm -f $(INSTALLED_PREBUILT_KERNEL_REPO_DIR)/*.ko
	cp `find $(PRODUCT_OUT)/obj/KERNEL_OBJ/ -type f -name "*.ko"` $(INSTALLED_PREBUILT_KERNEL_REPO_DIR)/
	cp $(PRODUCT_OUT)/kernel $@

.PHONY: prebuilt-kernel-repo
prebuilt-kernel-repo: $(INSTALLED_PREBUILT_KERNEL_REPO_KERNEL_TARGET)

endif # $(TARGET_KERNEL_SOURCE)/Makefile
endif # LINEAGE_BUILD

endif
